name: Test Addition Script

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test_addition:
    runs-on: ubuntu-latest  # The operating system for the GitHub runner

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Fetch the repository code

      - name: Set up Python 3.9
        uses: actions/setup-python@v4  # Set up Python 3.9
        with:
          python-version: '3.9'

      - name: Run addition script
        run: |
          python add_numbers.py  
